### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'model'

### ISSUE THREAD

**Issue by oblek** [MeaningCloud/meaningcloud-python#1]
I'm trying to use the sentiment analysis in python with the library provided
`sentiment_response = meaningcloud.SentimentResponse(meaningcloud.SentimentRequest(license_key, lang='en', txt=text, txtf='plain', model='Twitter').sendReq())`

but it fails when using the argument "model" with the following error message
TypeError: __init__() got an unexpected keyword argument 'model'

Is something wrong with the call I'm making or it is not implemented yet?

**Comment by bgalego** [comment]
The problem is that the SentimentRequest object does not receive "model" as a parameter. The model should be specified like this:

`sentiment_response = meaningcloud.SentimentResponse(meaningcloud.SentimentRequest(license_key, lang='en', txt=text, txtf='plain', otherparams={'model': 'your_model'}).sendReq())
`

If you want to use the general model provided, you don't need to specify it in the request as it's the default value. You can read more about the accepted values [here](https://www.meaningcloud.com/developer/sentiment-analysis/doc/2.1/request#sentiment-models-language).
